#!/usr/bin/env python3
"""Generate SDK types, runtime schemas, and reference from checked-in contracts."""
import argparse
import collections
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
check = argparse.ArgumentParser()
check.add_argument('--check', action='store_true')
args = check.parse_args()
c = json.loads((ROOT / 'docs/contracts.json').read_text())
selection = json.loads((ROOT / 'docs/operation-selection.json').read_text())
counts = collections.Counter(k.split('/')[-1].replace('$', '_') for k in c['models'])
names = {k: (k.split('/')[-1].replace('$', '_') if counts[k.split('/')[-1].replace('$', '_')] == 1 else ''.join(p[:1].upper()+p[1:] for p in k.split('/')[-3:]).replace('$', '_')) for k in c['models']}
assert len(set(names.values())) == len(names)

def ts(t, prefix=''):
    k = t['kind']
    if k == 'ref': return prefix + names[t['name']]
    if k == 'array': return 'Array<' + ts(t['items'], prefix) + '>'
    if k == 'record': return 'Record<string, ' + ts(t['values'], prefix) + '>'
    return {'integer':'number | bigint', 'json':prefix+'JsonValue', 'binary':'Uint8Array', 'upload':'UploadBody'}.get(k,k)

outputs = {}
header = '// Generated by scripts/generate-sdk.py from docs/contracts.json. Do not edit.\n'
model_lines = [header, '/** JSON values where the APK deliberately declares java.lang.Object. */',
               'export type JsonValue = string | number | bigint | boolean | null | JsonValue[] | { [key: string]: JsonValue };\n']
for key, model in c['models'].items():
    model_lines += [f'/** Wire fields from {key}. Missing fields with Kotlin defaults stay optional. */', f'export interface {names[key]} {{']
    for name, f in model['fields'].items():
        model_lines += [f'  {json.dumps(name)}{"" if f["required"] else "?"}: {ts(f["type"])}{" | null" if f["nullable"] else ""};']
    model_lines += ['}\n']
outputs['src/familysearch/generated/models.ts'] = '\n'.join(model_lines)

lines = [header, "import type * as M from './models.js';", "import type { UploadBody } from '../transport-types.js';", 'export interface OperationTypes {']
for op in c['operations']:
    lines += [f'  /** {op["method"]} {op["path"]} */', f'  {json.dumps(op["name"])}: {{ input: {{']
    for p in op['parameters']:
        if p['kind'] in ['path','body']:
            body_type = 'string' if op['name']=='memories.replaceFile' and p['kind']=='body' else ts(p['type'],'M.')
            lines += [f'    {json.dumps(p["name"])}: {body_type};']
    for kind, field in [('query','query'),('header','headers')]:
        params = [p for p in op['parameters'] if p['kind']==kind]
        if params:
            lines += [f'    {field}?: {{']
            for p in params: lines += [f'      {json.dumps(p["name"])}?: {ts(p["type"],"M.")};']
            lines += ['    };']
    lines += [f'  }}; output: {ts(op["response"],"M.")}{" | undefined" if op.get("responseOptional") else ""}; }};']
lines += ['}', 'export type OperationName = keyof OperationTypes;',
          "export type OperationInput<K extends OperationName> = OperationTypes[K]['input'];",
          "export type OperationOutput<K extends OperationName> = OperationTypes[K]['output'];",
          'export type OperationArgs<K extends OperationName> = {} extends OperationInput<K> ? [input?: OperationInput<K>] : [input: OperationInput<K>];',
          "type Group = OperationName extends `${infer G}.${string}` ? G : never;",
          'export type GenealogyApi = { [G in Group]: { [K in OperationName as K extends `${G}.${infer Method}` ? Method : never]: (...args: OperationArgs<K>) => Promise<OperationOutput<K>> } };\n']
outputs['src/familysearch/generated/operations.ts'] = '\n'.join(lines)

runtime = {'operations': {o['name']: {k:v for k,v in o.items() if k!='evidence'} for o in c['operations']},
           'models': {k:v['fields'] for k,v in c['models'].items()}}
outputs['src/familysearch/generated/schema.ts'] = header + "import type { ContractData } from '../contract-types.js';\nexport const contracts: ContractData = " + json.dumps(runtime, separators=(',',':')) + ';\n'

doc = ['# Genealogy operation reference', '', 'Generated from APK 5.4.4 contracts. Use `client.genealogy.<group>.<method>(input)` or `client.operation(name, input)`.',
       '', 'Path values and `body` are top-level input properties. Optional query/header values go inside `query` / `headers`. Their omission is supported by Retrofit; server requirements may be stricter. All path values are accepted unescaped and encoded once by this client.',
       '', 'A model’s required fields reflect the APK decoder. Optional non-null fields can be absent because the app has a default. Server-side create/update requirements can differ. Unknown response fields are preserved. See [contracts.json](contracts.json) for every nested field, nullability, and source provenance, and [generated types](../src/familysearch/generated/models.ts) for TypeScript.',
       '', 'Use `client.operationDetailed()` for status, headers, and binary downloads. Response bodies for `void` operations are drained and discarded. `JsonValue` means the APK itself declares an unstructured acknowledgement.', '']
for group in sorted({o['name'].split('.')[0] for o in c['operations']}):
    doc += [f'## {group}', '', '| Operation | HTTP path | Inputs | Response |', '| --- | --- | --- | --- |']
    for o in c['operations']:
        if not o['name'].startswith(group+'.'): continue
        inputs = '; '.join(p['kind']+': '+p['name']+' '+('string (raw story text)' if o['name']=='memories.replaceFile' and p['kind']=='body' else ts(p['type'])) for p in o['parameters']) or '—'
        output_type = ts(o['response']) + (' | undefined (HTTP 204)' if o.get('responseOptional') else '')
        doc += [f'| `{o["name"]}` | {o["method"]} `{o["path"]}` | {inputs.replace(chr(124), chr(92)+chr(124))} | {output_type.replace(chr(124), chr(92)+chr(124))} |']
    doc += ['']
outputs['docs/operations.md'] = '\n'.join(doc)

inventory = json.loads((ROOT / 'docs/endpoints.json').read_text())['endpoints']
selected_keys = {(o['method'],o['path']) for o in selection['operations']}
canonical = lambda o: o['method']+' '+re.sub(r'\{[^}]+\}', '{}', o['path'])
groups = []
for group in sorted({o['name'].split('.')[0] for o in selection['operations']}):
    members = [o for o in selection['operations'] if o['name'].startswith(group+'.')]
    groups.append({'group':group,'selected':len(members),'implemented':sum(not o.get('unsupported') for o in members)})
coverage = {'apkVersion':c['apkVersion'], 'scope': c['scope'], 'inventoryDeclarations':len(inventory),
            'selectedOperations':len(selection['operations']), 'implementedOperations':len(c['operations']),
            'selectedCanonicalRoutes':len({canonical(o) for o in selection['operations']}),
            'implementedCanonicalRoutes':len({canonical(o) for o in c['operations']}),
            'models':len(names), 'fields':sum(len(m['fields']) for m in c['models'].values()), 'groups':groups,
            'gaps':[o for o in selection['operations'] if o.get('unsupported')],
            'unstructuredResponses':[o['name'] for o in c['operations'] if o['response']['kind']=='json'],
            'excludedFromGenealogyScope':[{'method':e['method'],'path':e['path']} for e in inventory if (e['method'],e['path']) not in selected_keys]}
outputs['docs/coverage.json'] = json.dumps(coverage,indent=2)+'\n'
report = ['# Genealogy coverage', '',
          f'{len(c["operations"])} of {len(selection["operations"])} selected genealogy operations have callable TypeScript methods, request/response models, input validation, and mocked transport tests. These correspond to {coverage["implementedCanonicalRoutes"]} distinct HTTP method/path templates (placeholder names normalized).', '',
          'The denominator is the documented genealogy scope in [operation-selection.json](operation-selection.json), selected from all '+str(len(inventory))+' captured declarations. It includes research data, memories, source linking, relationship changes, history, family groups, helper permissions, and ordinance research. Messaging, event discovery, account administration, app infrastructure, location support, and appointment scheduling are excluded. This is not a claim to cover every FamilySearch backend or website service.', '',
          f'{len(names)} recovered models describe {coverage["fields"]} wire fields. Requiredness and field nullability come from the APK’s Moshi serializers. Request bodies are validated recursively; server business rules are enforced by FamilySearch. Response fields are retained and numeric/string conversions match the app’s reader. Java long values beyond the safe JavaScript range use bigint.', '',
          '| Area | Implemented / selected operations |','| --- | --- |']
report += [f'| {g["group"]} | {g["implemented"]} / {g["selected"]} |' for g in groups]
report += ['', '## Evidence and limits', '',
           '- Every implemented operation is exercised through the real authenticated transport with mocked responses; routes, verbs, path/query/header/body placement, and response handling are checked against the separate APK inventory.',
           '- Compile-time tests check required fields, invalid names and query types, nested bodies, and inferred outputs. Transport tests cover bounded 401 refresh, no retries of ambiguous writes, multipart uploads, raw stories, binary downloads, 204 responses, exact 64-bit numbers, and pagination.',
           '- Live verification is opt-in and account-dependent (`npm run verify:genealogy`). Reports are saved privately, never used as generator inputs. Offline coverage does not imply live service availability.',
           '- `trees.switch` is the one selected gap: its obfuscated SelectedGroupTreeDto has no recovered wire serializer. Its endpoint is inventoried, but the SDK does not guess its field names.',
           '- `sources.attachRecord` has a fully mapped request but an unstructured acknowledgement (`java.lang.Object` in the APK); its output is JsonValue.',
           '- Some permissions and server prerequisites vary by account and tree. 202 is exposed as pending HTTP status by operationDetailed; iterators do not promise a stable snapshot. Returned content links do not grant authorization to send bearer credentials to other hosts.',
           '- The inventory includes two common-service event preference declarations previously omitted. Bundled third-party chat APIs and dynamically constructed URLs are outside this genealogy surface. The APK itself was not executed.', '',
           '## Reproduction', '', '```sh', 'python3 scripts/extract-endpoints.py  # requires ignored smali', 'python3 scripts/extract-contracts.py  # requires ignored partial Java serializers', 'npm run generate                   # requires only checked-in contracts', 'npm run check:generated', 'npm run typecheck', 'npm run test:types', 'npm test', 'npm run build', 'npm run verify:genealogy            # optional authenticated read-only checks', '```', '',
           'The full method/path list and exclusions are machine-readable in [coverage.json](coverage.json). See [operations.md](operations.md) for each callable method and [contracts.json](contracts.json) for nested field schemas and source hashes.']
outputs['docs/coverage.md'] = '\n'.join(report)+'\n'

for path, text in outputs.items():
    target = ROOT / path
    text = text.rstrip()+'\n'
    if args.check:
        assert target.exists() and target.read_text()==text, f'Generated file is stale: {path}'
    else:
        target.parent.mkdir(parents=True,exist_ok=True)
        target.write_text(text)
print(('Checked' if args.check else 'Generated')+f' {len(c["operations"])} operations, {len(names)} models, {sum(len(m["fields"]) for m in c["models"].values())} wire fields.')
