#!/usr/bin/env python3
"""Regenerate provider TypeScript catalogs from checked-in JSON, without APK artifacts."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for service in ('ancestry', 'myheritage'):
    contracts = json.loads((ROOT / f'docs/{service}/contracts.json').read_text())
    content = (f'// Generated by scripts/extract-{service}.py. Do not edit.\n'
               'export const contracts = ' + json.dumps(contracts, indent=2) + ' as const;\n')
    target = ROOT / f'src/{service}/generated/contracts.ts'
    if args.check:
        if target.read_text() != content:
            raise SystemExit(f'Generated file is stale: {target.relative_to(ROOT)}')
    else:
        target.write_text(content)
    print(f'{service}: {len(contracts["rest"])} REST declarations, {len(contracts["graphql"])} GraphQL documents')
