#!/usr/bin/env python3
"""Regenerate provider TypeScript catalogs from checked-in JSON, without APK artifacts."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for service in ('ancestry', 'myheritage', 'findmypast', 'findagrave'):
    contracts = json.loads((ROOT / f'docs/{service}/contracts.json').read_text())
    content = (f'// Generated by scripts/extract-{service}.py. Do not edit.\n'
               'export const contracts = ' + json.dumps(contracts, indent=2) + ' as const;\n')
    target = ROOT / f'src/{service}/generated/contracts.ts'
    if args.check:
        if target.read_text() != content:
            raise SystemExit(f'Generated file is stale: {target.relative_to(ROOT)}')
    else:
        target.write_text(content)
    routes = (f'{len(contracts["rest"])} REST declarations' if 'rest' in contracts
              else f'{len(contracts["httpCallSites"])} HTTP call sites')
    print(f'{service}: {routes}, {len(contracts["graphql"])} GraphQL documents')

# Geneanet contracts come from the website; there is no APK extraction requirement.
service = 'geneanet'
contracts = json.loads((ROOT / 'docs/geneanet/contracts.json').read_text())
content = ('// Generated by scripts/generate-catalogs.py. Do not edit.\n'
           'export const contracts = ' + json.dumps(contracts, indent=2) + ' as const;\n')
target = ROOT / 'src/geneanet/generated/contracts.ts'
if args.check:
    if target.read_text() != content:
        raise SystemExit(f'Generated file is stale: {target.relative_to(ROOT)}')
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
print(f'geneanet: {len(contracts["operations"])} traced reads, {len(contracts["routes"])} catalog-only route declarations')
